services:
  - type: web
    name: wedding-backend
    env: docker
    region: frankfurt
    plan: starter
    dockerContext: ./backend
    dockerfilePath: ./backend/Dockerfile
    envVars:
      - key: PORT
        value: 3001
      - key: MONGO_URI
        value: null
      - key: JWT_SECRET
        value: null
      - key: GOOGLE_CLIENT_ID
        value: null
      - key: GOOGLE_CLIENT_SECRET
        value: null
      - key: AWS_ACCESS_KEY_ID
        value: null
      - key: AWS_SECRET_ACCESS_KEY
        value: null
      - key: AWS_REGION
        value: null
      - key: AWS_S3_BUCKET
        value: null

  - type: web
    name: wedding-frontend
    env: docker
    region: frankfurt
    plan: starter
    dockerContext: ./frontend
    dockerfilePath: ./frontend/Dockerfile
